---
kind: pipeline
name: amd86

steps:
- name: test
  image: golang
  commands:
  - go build

- name: publish
  image: plugins/docker
  settings:
    repo: savoiringfaire/overseerr-prom-exporter
    auto_tag: true
    auto_tag_suffix: linux-amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
      
---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: test
  image: golang
  commands:
  - go build

- name: publish
  image: plugins/docker
  settings:
    repo: savoiringfaire/overseerr-prom-exporter
    auto_tag: true
    auto_tag_suffix: linux-arm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
      
---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: golang
  commands:
  - go build

- name: publish
  image: plugins/docker
  settings:
    repo: savoiringfaire/overseerr-prom-exporter
    auto_tag: true
    auto_tag_suffix: linux-arm64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
name: docker-manifest

depends_on:
  - arm64
  - arm
  - amd86

steps:
  - name: manifest
    image: plugins/manifest
    settings:
      auto_tag: true
      ignore_missing: true
      spec: docker/manifest.tmpl
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
