kind: pipeline

steps:
- name: test
  image: golang
  commands:
  - go build

- name: publish
  image: plugins/docker
  settings:
    repo: savoiringfaire/overseerr-prom-exporter
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password